- hosts: all
  tasks:
    - debug:
        msg: "{{ zuul.change }}"
      when: zuul.change is defined
    - debug:
        msg: "{{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"
      when: zuul.change is defined
    - debug:
         msg: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    - name: Upload logs to log server
      synchronize:
        mode: pull
        src: /home/ec2-user/junitreportgeneration/target/site/surefire-report.html
        dest: /usr/local/apache2/htdocs/96/96/8c0b22d783d3aef0577c163761032f7026cb7b92/check_emea/demomavenbuildjob/6b8fc1b/
      
