- hosts: all
  tasks:
    - debug:
        msg: "{{ zuul.executor.work_root }}"
      when: zuul.change is defined
    - debug:
        msg: "{{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"
      when: zuul.change is defined
    - debug:
         msg: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    - name: Ensure logs are readable before uploading
      delegate_to: localhost
      command: "chmod -R u=rwX,g=rX,o=rX {{ zuul.executor.log_root }}/"
      
    - name: Upload logs to log server
      fetch:
        src: /home/ec2-user/junitreportgeneration/target/site/surefire-report.html
        dest: {{ zuul.executor.work_root }}
        flat: yes
